// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *About → phrases1*
 */
export interface AboutDocumentDataPhrases1Item {
  /**
   * text1 field in *About → phrases1*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.phrases1[].text1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text1: prismic.RichTextField;

  /**
   * text2 field in *About → phrases1*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.phrases1[].text2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text2: prismic.RichTextField;

  /**
   * text3 field in *About → phrases1*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.phrases1[].text3
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text3: prismic.RichTextField;
}

/**
 * Item in *About → phrases2*
 */
export interface AboutDocumentDataPhrases2Item {
  /**
   * text1 field in *About → phrases2*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.phrases2[].text1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text1: prismic.RichTextField;

  /**
   * text2 field in *About → phrases2*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.phrases2[].text2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text2: prismic.RichTextField;

  /**
   * text3 field in *About → phrases2*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.phrases2[].text3
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text3: prismic.RichTextField;
}

type AboutDocumentDataSlicesSlice = ImageSlideSlice | About1Slice;

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Title1 field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.title1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title1: prismic.RichTextField;

  /**
   * Text1 field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.text1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text1: prismic.RichTextField;

  /**
   * Image1 field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.image1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image1: prismic.ImageField<never>;

  /**
   * Title2 field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.title2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title2: prismic.RichTextField;

  /**
   * Text2 field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.text2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text2: prismic.RichTextField;

  /**
   * Image2 field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.image2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image2: prismic.ImageField<never>;

  /**
   * Image3 field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.image3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image3: prismic.ImageField<never>;

  /**
   * Image4 field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.image4
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image4: prismic.ImageField<never>;

  /**
   * Title3 field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.title3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title3: prismic.RichTextField;

  /**
   * Text3 field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.text3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text3: prismic.RichTextField;

  /**
   * phrases1 field in *About*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.phrases1[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  phrases1: prismic.GroupField<Simplify<AboutDocumentDataPhrases1Item>>;

  /**
   * phrases2 field in *About*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.phrases2[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  phrases2: prismic.GroupField<Simplify<AboutDocumentDataPhrases2Item>>;

  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice> /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AboutDocumentData>, "about", Lang>;

/**
 * Item in *slideImage → title*
 */
export interface SlideimageDocumentDataTitleItem {}

/**
 * Content for slideImage documents
 */
interface SlideimageDocumentData {
  /**
   * image field in *slideImage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slideimage.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *slideImage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: slideimage.title[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  title: prismic.GroupField<Simplify<SlideimageDocumentDataTitleItem>>;
}

/**
 * slideImage document from Prismic
 *
 * - **API ID**: `slideimage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SlideimageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SlideimageDocumentData>,
    "slideimage",
    Lang
  >;

export type AllDocumentTypes = AboutDocument | SlideimageDocument;

/**
 * Default variation for About1 Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type About1SliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *About1*
 */
type About1SliceVariation = About1SliceDefault;

/**
 * About1 Shared Slice
 *
 * - **API ID**: `about1`
 * - **Description**: About1
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type About1Slice = prismic.SharedSlice<"about1", About1SliceVariation>;

/**
 * Primary content in *ImageSlide → Items*
 */
export interface ImageSlideSliceDefaultItem {
  /**
   * image field in *ImageSlide → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slide.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *ImageSlide → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_slide.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Default variation for ImageSlide Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlideSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ImageSlideSliceDefaultItem>
>;

/**
 * Slice variation for *ImageSlide*
 */
type ImageSlideSliceVariation = ImageSlideSliceDefault;

/**
 * ImageSlide Shared Slice
 *
 * - **API ID**: `image_slide`
 * - **Description**: ImageSlide
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageSlideSlice = prismic.SharedSlice<
  "image_slide",
  ImageSlideSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataPhrases1Item,
      AboutDocumentDataPhrases2Item,
      AboutDocumentDataSlicesSlice,
      SlideimageDocument,
      SlideimageDocumentData,
      SlideimageDocumentDataTitleItem,
      AllDocumentTypes,
      About1Slice,
      About1SliceVariation,
      About1SliceDefault,
      ImageSlideSlice,
      ImageSlideSliceDefaultItem,
      ImageSlideSliceVariation,
      ImageSlideSliceDefault,
    };
  }
}
