// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about1: dynamic(() => import("./About1")),
  image_slide: dynamic(() => import("./ImageSlide")),
};
